import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Inter', ...defaultTheme.fontFamily.sans],
                'headline-sm': ['Inter'],
                'body-lg': ['Inter'],
                'label-md': ['Inter'],
                'headline-md': ['Inter'],
                'headline-lg': ['Inter'],
                'body-md': ['Inter'],
                'headline-lg-mobile': ['Inter'],
            },
            colors: {
                'surface-variant': '#d3e4fe',
                'on-secondary': '#ffffff',
                'on-secondary-fixed-variant': '#005049',
                'surface-tint': '#006398',
                'surface-container-high': '#dce9ff',
                'on-secondary-container': '#006f66',
                'on-secondary-fixed': '#00201d',
                'on-error': '#ffffff',
                'on-primary': '#ffffff',
                'on-background': '#0b1c30',
                'primary-container': '#007bb9',
                'primary': '#006194',
                'inverse-on-surface': '#eaf1ff',
                'on-tertiary': '#ffffff',
                'on-surface-variant': '#3f4850',
                'tertiary-fixed-dim': '#c4c7c9',
                'on-primary-fixed': '#001d31',
                'secondary': '#006a61',
                'surface-dim': '#cbdbf5',
                'tertiary-fixed': '#e0e3e5',
                'on-primary-container': '#fdfcff',
                'on-surface': '#0b1c30',
                'error-container': '#ffdad6',
                'surface-container': '#e5eeff',
                'primary-fixed-dim': '#93ccff',
                'inverse-surface': '#213145',
                'inverse-primary': '#93ccff',
                'outline-variant': '#bfc7d2',
                'secondary-fixed': '#89f5e7',
                'on-error-container': '#93000a',
                'on-tertiary-fixed-variant': '#444749',
                'secondary-fixed-dim': '#6bd8cb',
                'tertiary-container': '#727577',
                'surface-bright': '#f8f9ff',
                'on-tertiary-container': '#fbfdff',
                'on-primary-fixed-variant': '#004b73',
                'outline': '#707881',
                'on-tertiary-fixed': '#191c1e',
                'primary-fixed': '#cce5ff',
                'surface-container-low': '#eff4ff',
                'surface-container-lowest': '#ffffff',
                'error': '#ba1a1a',
                'surface': '#f8f9ff',
                'tertiary': '#595c5e',
                'background': '#f8f9ff',
                'surface-container-highest': '#d3e4fe',
                'secondary-container': '#86f2e4',
            },
            borderRadius: {
                'DEFAULT': '0.25rem',
                'lg': '0.5rem',
                'xl': '0.75rem',
                'full': '9999px',
            },
            spacing: {
                'gutter': '1.5rem',
                'stack-sm': '0.5rem',
                'sidebar-width': '260px',
                'margin-page': '2rem',
                'stack-md': '1rem',
                'stack-lg': '2rem',
            },
            fontSize: {
                'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
                'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
                'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
                'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
                'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
                'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
                'headline-lg-mobile': ['26px', { lineHeight: '32px', fontWeight: '700' }],
            },
        },
    },

    plugins: [forms],
};
